spring.application.name=cachingApp

spring.datasource.url=jdbc:postgresql://localhost:5432/cache
spring.datasource.username=postgres
spring.datasource.password=Long13@64

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#redis configurations
#spring.cache.type= redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.data.redis.host=drop-neoteric-dove-72933.db.redis.io
spring.data.redis.port=14662
spring.data.redis.password=Mc8V1st7IipW9YBNrwUhXCEAh367By7p
#spring.data.redis.ssl.enabled=false