spring.application.name=securityApp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.datasource.url=jdbc:mysql://localhost:3306/security-app?useSSL=false
spring.datasource.username=root
spring.datasource.password=Long13@64

#spring.security.user.name= hejazi
#spring.security.user.password= pass

jwt.secretKey= wjbyg4894r020r43845784gkjrbkjpotjv8y903it09u

